export const getEmployeesActionTypes = {
    FETCH_GETEMPLOYEES_REQUEST: "FETCH_GETEMPLOYEES_REQUEST",
    FETCH_GETEMPLOYEES_SUCCESS: "FETCH_GETEMPLOYEES_SUCCESS",
    FETCH_GETEMPLOYEES_FAILURE: "FETCH_GETEMPLOYEES_FAILURE",
};
