export const timesheetActionTypes = {
    FETCH_TIMESHEET_REQUEST: "FETCH_TIMESHEET_REQUEST",
    FETCH_TIMESHEET_SUCCESS: "FETCH_TIMESHEET_SUCCESS",
    APPROVE_REJECT_TIMESHEET_REQUEST: "APPROVE_REJECT_TIMESHEET_REQUEST",
    APPROVE_REJECT_TIMESHEET_SUCCESS: "APPROVE_REJECT_TIMESHEET_SUCCESS",
    APPROVE_REJECT_TIMESHEET_FAILURE: "APPROVE_REJECT_TIMESHEET_FAILURE",
};
